title: Foorier
description: "L'intelligence au cœur du bâtiment"
baseurl: "/foorier.website.github.io"
url: "https://philippekalousdian.github.io"
locale: "fr-FR"
lang: "fr"

# Theme settings
remote_theme: raviriley/agency-jekyll-theme

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
