title: Foorier
email: contact@foorier.fr
description: "L'intelligence au cœur du bâtiment - Pilotage énergétique intelligent des bâtiments tertiaires"
author: Foorier
baseurl: "/foorier.website.github.io"  # Nom du repo
url: "https://philippekalousdian.github.io"

# Social links
twitter_username: 
github_username: foorier
facebook_username: 
linkedin_username: foorier

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  
# Collections (si tu veux un blog)
collections:
  portfolio:
    output: true
    permalink: /solutions/:path/
