# Site settings
title: Foorier
email: contact@foorier.fr
description: "L'intelligence au cœur du bâtiment"
author: Foorier
baseurl: "/foorier.website.github.io"
url: "https://philippekalousdian.github.io"
locale: "fr-FR"
lang: fr

# Build settings
markdown: kramdown
permalink: pretty

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # foorier

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: # UA-XXXXXXXX-X

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/foorier

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Foorier"

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
